### ISSUE TITLE
11월 3째주 Todo

### ISSUE THREAD

**Issue by hanmolee** [jso4603/C-Language-Programming-Practice#1]
## 11월 3째주 Todo List

- [ ] C 언어 책 4, 5장 이해 및 예제 프로그래밍
- [ ] 예제 한개 할 때마다 Github에 올리기
- [ ] 일요일 저녁에 물어볼 내용 정리하기

**Comment by hanmolee** [comment]
Ex> 어제 했던 질문 중 (4-1은 예를 들뿐이다.)
- 4-1 예제 중에서 문자열을 출력하는데 %s, %c 의 차이를 모르겠다.

최소한 이정도로 기록을 바람
